# Generated by Django 5.1.6 on 2025-03-07 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_product_options_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзины'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
